services:
  postgres:
    image: postgres:16
    container_name: transit_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transit_app
      POSTGRES_USER: transit_user
      POSTGRES_PASSWORD: transit_password
    ports:
      - "5432:5432"
    volumes:
      - transit_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: transit_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  transit_postgres_data:
